
# Write my first ansible configuration file with enough messages. PLEASR DO THE
# JUST ENOUGH comments when introducting new things in ansible configurations(
# Such as *.yml, ansible.cfg and inventory.ini"
# Use the machines in defined in inventory.ini which is specified in ansible.cfg
- hosts: git
  tasks:
    # Call curl directly is not suggested by ansible. But I do not know how to
    # check the network connection when the url need to follow the location:
    # -L, --location
    #   (HTTP)  If  the server reports that the requested page
    #   has moved to a different location (indicated with a Location: header and a 3XX response code),
    - name: detect network
      shell: >
          curl -s --connect-timeout 2 baidu.com 2>/dev/null >/dev/null
    - name: detect GFW
      shell: >
          curl -s --connect-timeout 2 google.com 2>/dev/null >/dev/null
    # fetch and rebase. I called the git with --work-tree, but somethings it is
    # not worked. Use "cd" at the monment.
    # TODO: better exit messages when local changes exists.
    - name: git rebase
      shell:
        cd {{ ansible_env.HOME }}/works/open_log;
        git fetch;
        git rebase
      register: git_rebase_result
    # Output the git rebase output user may need the information
    - name: git rebase stdout
      debug:
        msg: "{{ git_rebase_result.stdout }}"
    - name: git push
      shell:
        cd {{ ansible_env.HOME }}/works/open_log;
        git push;

