
# Write my first ansible configuration file with enough messages. PLEASR DO THE
# JUST ENOUGH comments when introducting new things in ansible configurations(
# Such as *.yml, ansible.cfg and inventory.ini"
# Use the machines in defined in inventory.ini which is specified in ansible.cfg
- hosts: test
  # Get the minimal facts through setup. Otherwise, these tasks will fail at
  # ansible_env.HOME and raise the error The fatal error was: "'ansible_env' is
  # undefined"
  # <http://docs.ansible.com/ansible/latest/setup_module.html>
  gather_facts: no
  #  pre_tasks:
  #    - setup:
  #      gather_subset: min
  vars:
    home: /home/os01
    my_var:
        - {remote: 'https://github.com/96boards-hikey/tools-images-hikey960.git', path: 'works/source/96boards/hikey960/tools-images-hikey960'}
        - {remote: 'https://github.com/ARM-software/arm-trusted-firmware.git', path: 'works/source/96boards/hikey960/arm-trusted-firmware'}

  tasks:
#    - name: key value test
#      shell:
#          mkdir -p {{ home }}/{{ item.path }}
#      with_items: "{{ my_var }}"
    - name: clone if not exist
      git:
          repo: "{{ item.remote }}"
          dest: "{{ home }}/{{ item.path }}"
          clone: yes
          update: yes
      with_items: "{{ my_var }}"
