- hosts: all
  remote_user: root
  tasks:
#  - name: Generate SSH keys
#    shell: ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
#  - name: Copy ssh keys
#    #ssh root@192.168.122.242 "cat ~/.ssh/id_rsa.pub" | ssh bamvor@10.71.84.51 "cat >> ~/.ssh/authorized_keys"
  - name: add proxy
    shell:
      ssh -fNL 7228:localhost:7228 bamvor@10.71.84.51;
      MY_ENV="/etc/bash.bashrc";
      echo "export http_proxy=localhost:7228" >> $MY_ENV;
      echo "export https_proxy=localhost:7228" >> $MY_ENV
  - name: detect network
    shell:
        curl -s --connect-timeout 2 baidu.com 2>/dev/null >/dev/null
  - name: test
    zypper_repository:
        state: present
        auto_import_keys: yes
        repo: 'http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/openSUSE_Leap_42.3/Virtualization:Appliances:Builder.repo'
  - name: install the latest version of man
    zypper:
      name: man
      state: latest
  - name: install the latest version of jq
    zypper:
      name: jq
      state: latest
  - name: install the latest version of yum
    zypper:
      name: yum
      state: latest
  - name: install the latest version git
    zypper:
      name: git
      state: latest
  - name: install the latest version command-not-found
    zypper:
      name: command-not-found
      state: latest
  - name: install the latest version syslinuxgit
    zypper:
      name: syslinux
      state: latest
  - name: install screen
    zypper:
      name: screen
      state: latest
  - name: install createrepo
    zypper:
      name: createrepo
      state: latest
  - name: install xfsprogs for mkfs.xfs
    zypper:
      name: xfsprogs
      state: latest
  - name: install the latest version of kiwi
    zypper:
      name: python3-kiwi>=9.11
      state: latest
  
