=head1 NAME

xl.snapshot.cfg - XL Domain Snapshot Configuration File Syntax

=head1 DESCRIPTION

Without the snapshot configuration file, xl snapshot-create could create
internal domain snapshot or internal disk snapshot. To create a user-defined
domain snapshot, xl requires a domain snapshot config file. It is typically
located at `/var/lib/xen/snapshots/UUID/snapshotdata-d.NAME.libxl-json` where
UUID is the uuid of domain and the NAME is the snapshot name. See
snapshot-HOWTO.txt for use cases and examples.

=head1 SYNTAX

A domain config file consists of a series of C<KEY=VALUE> pairs. It shares the
same rules with xl.cfg

=head1 OPTIONS

=over 4

=item B<name="NAME">

Specifies the name of the domain snapshot. Names of snapshots existing in one
domain must be unique. If it is not provided, it will be the epoch second from
1, Jan 1970.

=item B<description="DESCRIPTION">

Optional. The snapshot description.

=item B<creationtime="CREATIONTIME">

The creation time of this snapshot. It will be the epoch second from 1, Jan
1970. This field could not be specified by user, it will be ignored in domain
snapshot creation.

=item B<memory="MEMORY">

Describes the location of memory save image. This image is as same as the image
in "xl save". The value could be the absolute path of the memory save image or
"yes" which means `/var/lib/xen/snapshots/UUID/NAME.save`. if it is "no" or is
not provied, this snapshot will be a disk only snapshot.

=item B<type="TYPE">

Describes the domain snapshot type. The possible value are "internal",
"external". if it is not provided, this snapshot will be a internal snapshot.
Note that each disk is allowed to choice their own snapshot type which is
determined by what information is provided in DISK_SPEC_STRING

=item B<disk=[ "DISK_SPEC_STRING", "DISK_SPEC_STRING", ...]>

The disk snapshot description. See F<docs/misc/xl-disk-configuration.txt> for
rules. For internal snapshot, user should only provide vdev. For external
snapshot, user should provide vdev, format and target. Format is the format of
external snapshot file, only qcow2 is allowed at this time. Target is disk file
after the external snapshot including absolute path.

=back

