#!/bin/bash
#by bamvor. used to add date and time to a file. It is good for your management 
#of log file. 
#usage:
#./shAddDateToFile hostfilename
# the command above means adding a new log message at the tail of the hostfile 
#whose name is hostfilename.
#./shAddDateToFile
# the command above means run in test mode, in which add a new log message at 
#the tail of a temporary host file. the script will output the whole result and
#delete the temporary file.
#date: 2006-11-10

#represant whether is a test mode or not.
isTestMode=False

if [ "$1" != "" ]; then
    hostFile=$1
    echo "using the first the parameter -- $hostFile as the hostfilename"
else
    echo "test mode. create a testHostFile"
    $isTestMode=True
    hostFile=host`date +%R`
    echo "This is a test file" >> $hostFile
fi

#create a new file which will add to the tail of the host file
newlogfile=`date +%k%M%S`
#create the date string. It will add to the host file, which in front of the
#file "$newlogfile"
dateString=`date +"%R %F"`

vim $newlogfile
echo $dateString >> $hostFile
cat $newlogfile >> $hostFile
echo >> $hostFile
echo "you input: "
cat $newlogfile
if [ "$isTestMode" = "True" ]; then
    echo "output the result: "
    cat $hostFile
fi
echo "delete files."
rm $newlogfile
if [ "$isTestMode" = "True" ]; then
    rm $hostFile
fi
echo "successful. program exit normally."

