#!/bin/bash

install_for_user()
{
    USER=$1
    if [ X$USER = Xroot ]; then
        UPATH="/$USER"
    else
        UPATH="/home/$USER"
    fi
    su $USER -c 'mkdir $UPATH/bin -p'
    for l in `ls --color=none utils`; do
        su $USER -c 'ln -sf `realpath utils/$l` $UPATH/bin'
    done

    su $USER -c 'cp -a misc/tmux.conf $UPATH/.tmux.conf'
}

echo "This script is not finished!!!!"
USER=$1

if [ X$USER = X ]; then
	echo "User is empty, exit"
fi

echo "Install software"
echo "install tmux"
sudo zypper --non-interactive install tmux
echo "install cscope"
sudo zypper --non-interactive install cscope
echo "instal qemu-system-aarch64"
sudo zypper --non-interactive --gpg-auto-import-keys addrepo -c -f -r http://download.opensuse.org/repositories/Virtualization/openSUSE_Leap_42.1/Virtualization.repo
sudo zypper --non-interactive  --gpg-auto-import-keys refresh
sudo zypper --non-interactive  --gpg-auto-import-keys install qemu-arm

sudo su -c 'cat vim/vimrc >> /etc/vimrc'
sudo cp -a vim/plugin vim/doc /usr/share/vim/current/
sudo su -c 'echo ". $PWD/bash/gdb_debug" >> /etc/bash.bashrc'
sudo su -c 'echo ". $PWD/bash/logAssistant_helper" >> /etc/bash.bashrc'
sudo su -c 'echo ". $PWD/bash/indent-libvirt" >> /etc/bash.bashrc'
sudo su -c 'echo "export GIT_EXTERNAL_DIFF=~/bin/git_diff_wrapper" >> /etc/bash.bashrc'
sudo su -c 'cat ssh_config >> /etc/ssh/ssh_config'
sudo su -c 'cat hosts >> /etc/hosts'

install_for_user $USER
#install_for_user root

