#!/bin/bash
echo "This script is not finished!!!!"

#exit

USER=$1

if [ X$USER = X ]; then
	echo "User is empty, exit"
fi

#cat vim/vimrc >> /etc/vimrc
#cp -a vim/plugin vim/doc /usr/share/vim/current/
echo ". $PWD/bash/gdb_debug" >> /etc/bash.bashrc
echo ". $PWD/bash/logAssistant_helper" >> /etc/bash.bashrc
echo ". $PWD/bash/indent-libvirt" >> /etc/bash.bashrc
echo "export GIT_EXTERNAL_DIFF=~/bin/git_diff_wrapper" >> /etc/bash.bashrc

#list="
#utils/build_arm.sh
#utils/git_diff_wrapper
#utils/log.sh
#utils/osc_bl
#utils/osc_bl_sp2_x86_64
#utils/osc_bl_sp3_x86_64
#utils/osc_r
#utils/osc_r_sp2_x86_64
#utils/osc_r_sp3_x86_64
#utils/search.sh
#"
#mkdir /home/$USER/bin -p
#for l in $list; do
#	ln -sf $PWD/$l /home/$USER/bin
#done
#
#
#cp -a misc/tmux.conf /home/$USER/.tmux.conf
#
