#!/bin/bash

while true; do
    result=`osc r | grep $1 | grep $2`
    echo $result | grep "\(succeed\)\>\|\(failed\)\>" && break || echo wait $result
    result=$?
    sleep 2
done

if [ "$result" == "0" ]; then
    exit 1
fi
